# Generated by Django 4.1.5 on 2023-01-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name_plural": "Feedback"},
        ),
        migrations.AddField(
            model_name="feedback",
            name="url",
            field=models.CharField(blank=True, default="", max_length=600),
        ),
    ]
