# Generated by Django 4.1.5 on 2023-01-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_rename_ftype_feedback_feedbacktype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="text",
            new_name="message",
        ),
    ]
