# Generated by Django 4.1.5 on 2023-01-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_rename_text_feedback_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="feedbackType",
            new_name="feedback_type",
        ),
    ]
