# Generated by Django 4.1.5 on 2023-02-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_alter_feedback_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date at which this message was recorded",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.CharField(help_text="User's email", max_length=400),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(
                help_text="Feedback type, be it a suggestion or an error.",
                max_length=400,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(help_text="A text of user's message."),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date at which this message was changed by someone with write access",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Page URL for the feedback",
                max_length=600,
            ),
        ),
    ]
